export interface Manufacturer {
  id: number;
  name: string;
  role: string;
  region: 'Canada' | 'Ireland' | 'UK' | 'Europe' | 'USA' | 'China';
  location: string;
  website: string;
  certifications: string[];
  contact: string;
  cottonRelevance: string;
  highlight?: string;
}

export const manufacturers: Manufacturer[] = [
  // === TIER 1: Already make cotton nasal / nosebleed products ===
  {
    id: 1,
    name: 'Richmond Dental & Medical',
    role: 'Cotton nosebleed plugs, dental cotton rolls, cotton pellets, wound packing',
    region: 'USA',
    location: 'Charlotte, NC, USA',
    website: 'https://richmonddentalandmedical.com',
    certifications: ['ISO 13485', 'FDA Registered'],
    contact: 'Via website — they do private-label / contract manufacturing',
    cottonRelevance: 'Already manufactures cotton nosebleed plugs and braided cotton rolls. Closest existing product to SnugBug. Ask about private-label or contract manufacturing for a pediatric cotton nasal insert.',
    highlight: 'ALREADY MAKES NOSEBLEED PLUGS',
  },
  {
    id: 2,
    name: 'Nampons (Bio-Nasal LLC)',
    role: 'Direct competitor — cotton-based nosebleed plugs for children and adults',
    region: 'USA',
    location: 'USA',
    website: 'https://nampons.com',
    certifications: ['FDA Registered'],
    contact: 'Via website',
    cottonRelevance: 'Direct competitor selling cotton nosebleed plugs. Study their supply chain — they likely contract-manufacture. Investigating their manufacturer could reveal a potential partner.',
    highlight: 'COMPETITOR — STUDY',
  },

  // === TIER 2: Medical cotton manufacturers who could adapt to nasal ===
  {
    id: 3,
    name: 'Robinson Healthcare',
    role: 'Cotton wool rolls, balls, pleats, medical swabs — UK\'s largest cotton medical manufacturer',
    region: 'UK',
    location: 'Chesterfield, UK',
    website: 'https://robinsonhealthcare.com',
    certifications: ['ISO 13485', 'CE Marked', 'MHRA Registered'],
    contact: 'Via website — does contract manufacturing and private label',
    cottonRelevance: 'One of the UK\'s oldest and largest medical-grade cotton processors. Specialise in cotton wool products. Strong fit for private-label cotton nasal insert manufacturing for UK/EU markets.',
    highlight: 'TOP PICK FOR UK/EU COTTON',
  },
  {
    id: 4,
    name: 'Medicom Group',
    role: 'Medical cotton rolls, cotton balls, infection control products',
    region: 'Canada',
    location: 'Montreal, Canada (HQ); multi-country manufacturing',
    website: 'https://medicom.com',
    certifications: ['ISO 13485', 'CE Marked', 'FDA Registered', 'Health Canada'],
    contact: 'Corporate HQ Montreal; sales via website',
    cottonRelevance: 'Major Canadian medical consumables company with cotton product expertise. Could manufacture cotton nasal inserts at scale with Health Canada compliance built in.',
    highlight: 'TOP PICK FOR CANADA',
  },
  {
    id: 5,
    name: 'Lohmann & Rauscher',
    role: 'Cotton wool, absorbent cotton, surgical cotton, wound care',
    region: 'Europe',
    location: 'Vienna, Austria / Rengsdorf, Germany',
    website: 'https://lohmann-rauscher.com',
    certifications: ['ISO 13485', 'CE Marked', 'EU MDR'],
    contact: 'Multiple European offices; contract manufacturing via website',
    cottonRelevance: 'Major European medical cotton and wound care manufacturer. Deep expertise in absorbent cotton processing. Good partner for EU MDR-compliant cotton nasal product.',
  },
  {
    id: 6,
    name: 'Hartmann Group (Paul Hartmann AG)',
    role: 'Cotton wool, absorbent cotton, wound care dressings, surgical cotton',
    region: 'Europe',
    location: 'Heidenheim, Germany',
    website: 'https://hartmann.info',
    certifications: ['ISO 13485', 'CE Marked', 'EU MDR'],
    contact: 'Multiple European offices',
    cottonRelevance: 'Major European medical cotton manufacturer with long history. Produces cotton wool and absorbent cotton products at scale. Strong for EU manufacturing.',
  },
  {
    id: 7,
    name: 'Vernacare',
    role: 'Cotton wool balls, cotton wool rolls, medical cotton products',
    region: 'UK',
    location: 'Bolton, Lancashire, UK',
    website: 'https://vernacare.com',
    certifications: ['ISO 13485', 'CE Marked'],
    contact: 'Via website — NHS supplier',
    cottonRelevance: 'UK-based medical cotton manufacturer and NHS supplier. Could produce cotton nasal inserts for UK market with existing cotton processing capabilities.',
  },
  {
    id: 8,
    name: 'Sterimed Group',
    role: 'Medical-grade cotton, absorbent cotton, surgical dressings, cotton wool',
    region: 'Europe',
    location: 'Paris, France',
    website: 'https://sterimed.fr',
    certifications: ['ISO 13485', 'CE Marked'],
    contact: 'Via website',
    cottonRelevance: 'Significant European cotton medical products manufacturer. Produces absorbent cotton and surgical cotton dressings. Potential partner for cotton nasal insert production in France.',
  },
  {
    id: 9,
    name: 'Rocialle Healthcare',
    role: 'Cotton wool balls, cotton gauze, surgical cotton, procedure pack assembly',
    region: 'UK',
    location: 'South Wales, UK',
    website: 'https://rocialle.co.uk',
    certifications: ['ISO 13485', 'CE Marked'],
    contact: 'Via website — NHS supplier',
    cottonRelevance: 'UK manufacturer doing custom procedure pack assembly with cotton products. Could assemble and package a cotton nasal insert product.',
  },
  {
    id: 10,
    name: 'JMU (Jian Mei United)',
    role: 'Dental cotton rolls, cotton pellets, cotton-tipped applicators, gauze',
    region: 'China',
    location: 'Foshan, Guangdong, China',
    website: 'https://jmudental.com',
    certifications: ['ISO 13485', 'CE Marked', 'FDA Registered'],
    contact: 'Via website — does OEM/ODM manufacturing',
    cottonRelevance: 'Mass producer of dental cotton rolls — essentially the same form as a nasal insert. High-volume, cost-effective. Many white-label dental cotton products come from JMU. CE marked for EU export.',
  },
  {
    id: 11,
    name: 'Winner Medical',
    role: 'Medical cotton products, cotton wound dressings (Purcotton), absorbent cotton',
    region: 'China',
    location: 'Shenzhen, China (EU distribution)',
    website: 'https://winnermedical.com',
    certifications: ['ISO 13485', 'CE Marked', 'FDA Registered'],
    contact: 'Via website — does OEM',
    cottonRelevance: 'Massive cotton medical product manufacturer. Their Purcotton brand is well-known for pure cotton products. Does OEM manufacturing with CE marking for EU market.',
  },

  // === Original list — kept if cotton-relevant ===
  {
    id: 12,
    name: 'Gentell',
    role: 'Wound care manufacturer — cotton-based products',
    region: 'Canada',
    location: 'Canada (plus Brazil, China, NZ, UK)',
    website: 'https://gentell.com',
    certifications: [],
    contact: 'Contact via gentell.com',
    cottonRelevance: 'Manufactures traditional wound care supplies including cotton-based products. Multi-country production could support cotton insert manufacturing.',
  },
  {
    id: 13,
    name: 'Urgo Medical',
    role: 'French wound care manufacturer — cotton-based dressings',
    region: 'Europe',
    location: 'Chenove, France (HQ)',
    website: 'https://urgomedical.us',
    certifications: [],
    contact: 'Contact via website',
    cottonRelevance: 'Major French wound care company producing cotton-based dressings. Potential co-manufacturing partner for cotton nasal product in Europe.',
  },
  {
    id: 14,
    name: 'Ensera (formerly SteriPack)',
    role: 'Global CDMO — contract packing, cleanroom manufacturing',
    region: 'Ireland',
    location: 'Dublin / Limerick, Ireland',
    website: 'https://ensera.com',
    certifications: ['ISO 13485', 'FDA Registered', 'GMP', 'Health Canada'],
    contact: '+353 61 358 190 / ensera.com/contact',
    cottonRelevance: 'Not a cotton manufacturer, but ideal for sterile packaging and assembly of cotton nasal inserts once manufactured. 30+ year CDMO with GMP cleanrooms. Pair with a cotton supplier.',
  },
  {
    id: 15,
    name: 'Command Medical Products',
    role: 'Contract manufacturer — sterile packaging, assembly',
    region: 'Canada',
    location: 'Barrie, Ontario, Canada',
    website: 'https://commandmedical.com',
    certifications: ['ISO 13485', 'FDA Registered'],
    contact: 'Contact form at commandmedical.com',
    cottonRelevance: 'Not a cotton manufacturer, but good for sterile packaging of cotton nasal inserts if sourcing cotton component separately. Canadian manufacturing base.',
  },
];
